sed -i 's/^Accounting.Club/1/i' organization-officers.tsv
sed -i 's/^Adaa/2/i' organization-officers.tsv
sed -i 's/^AF.Theatre.Company/3/i' organization-officers.tsv
sed -i 's/^African.Student.Association/4/i' organization-officers.tsv
sed -i 's/^Africana.Council/5/i' organization-officers.tsv
sed -i 's/^Agape.Campus.Christian.Fellowship/6/i' organization-officers.tsv
sed -i 's/^Aikido.Club/7/i' organization-officers.tsv
sed -i 's/^AIM..Achievement.and.Inspiration.through.Mentorship./8/i' organization-officers.tsv
sed -i 's/^AISH.UMBC/9/i' organization-officers.tsv
sed -i 's/^Alpha.Kappa.Alpha.Sorority.Inc...Lambda.Phi.Chapter/10/i' organization-officers.tsv
sed -i 's/^Alpha.Kappa.Delta.Phi.International.Sorority..Inc./11/i' organization-officers.tsv
sed -i 's/^Alpha.Phi.Alpha.Fraternity..Inc./12/i' organization-officers.tsv
sed -i 's/^Alpha.Phi.Omega/13/i' organization-officers.tsv
sed -i 's/^Alpha.Sigma.Alpha/14/i' organization-officers.tsv
sed -i 's/^Alpha.Sigma.Kappa/15/i' organization-officers.tsv
sed -i 's/^Amateur.Radio.Club/16/i' organization-officers.tsv
sed -i 's/^American.Institute.of.Aeronautics.and.Astronautics..AIAA...The/17/i' organization-officers.tsv
sed -i 's/^American.Institute.of.Chemical.Engineers..AIChE./18/i' organization-officers.tsv
sed -i 's/^American.Red.Cross.Club/19/i' organization-officers.tsv
sed -i 's/^American.Society.of.Mechanical.Engineers/20/i' organization-officers.tsv
sed -i 's/^Amnesty.International/21/i' organization-officers.tsv
sed -i 's/^Ampersand.Creative.Writing.Club/22/i' organization-officers.tsv
sed -i 's/^Ancient.Studies.Council/23/i' organization-officers.tsv
sed -i 's/^Anime.Society/24/i' organization-officers.tsv
sed -i 's/^Arab.Student.Union/25/i' organization-officers.tsv
sed -i 's/^Archery.Club/26/i' organization-officers.tsv
sed -i 's/^Army.R.O.T.C./27/i' organization-officers.tsv
sed -i 's/^Art.Club/28/i' organization-officers.tsv
sed -i 's/^Asian.Studies.Council.of.Majors/29/i' organization-officers.tsv
sed -i 's/^Astronomy.Club/30/i' organization-officers.tsv
sed -i 's/^Bartleby..The.Creative.Arts.Journal.of.UMBC./31/i' organization-officers.tsv
sed -i 's/^Bengali.Student.Council/32/i' organization-officers.tsv
sed -i 's/^Best.Buddies/33/i' organization-officers.tsv
sed -i 's/^Bethel.Campus.Fellowship/34/i' organization-officers.tsv
sed -i 's/^Beyond.Relief/35/i' organization-officers.tsv
sed -i 's/^Bhagavad.Gita.Club/36/i' organization-officers.tsv
sed -i 's/^Billiards.Club/37/i' organization-officers.tsv
sed -i 's/^Biology.Council.of.Majors/38/i' organization-officers.tsv
sed -i 's/^Black.Lives.Matter/39/i' organization-officers.tsv
sed -i 's/^Black.Student.Union/40/i' organization-officers.tsv
sed -i 's/^CamDi..Campus.Disciples./41/i' organization-officers.tsv
sed -i 's/^Caribbean.Students.Council/42/i' organization-officers.tsv
sed -i 's/^Catholic.Retrievers/43/i' organization-officers.tsv
sed -i 's/^Charm.City.Connection..The/44/i' organization-officers.tsv
sed -i 's/^Chemistry.Biochemistry.Council.of.Majors/45/i' organization-officers.tsv
sed -i 's/^Chess.Club/46/i' organization-officers.tsv
sed -i 's/^Chi.Alpha.Christian.Fellowship/47/i' organization-officers.tsv
sed -i 's/^Chinese.Students.Association/48/i' organization-officers.tsv
sed -i 's/^Chinmaya.Yuva.Kendra..CHYK./49/i' organization-officers.tsv
sed -i 's/^Circle.K/50/i' organization-officers.tsv
sed -i 's/^Cleftomaniacs/51/i' organization-officers.tsv
sed -i 's/^Club.Cheer/52/i' organization-officers.tsv
sed -i 's/^Code.Life/53/i' organization-officers.tsv
sed -i 's/^College.Democrats/54/i' organization-officers.tsv
sed -i 's/^College.Republicans/55/i' organization-officers.tsv
sed -i 's/^Comics.and.Other.Media..com./56/i' organization-officers.tsv
sed -i 's/^Computer.Science.Education/57/i' organization-officers.tsv
sed -i 's/^Connect/58/i' organization-officers.tsv
sed -i 's/^Constitutional.Retrievers/59/i' organization-officers.tsv
sed -i 's/^Coptic.Club/60/i' organization-officers.tsv
sed -i 's/^Cosplay.Coalition/61/i' organization-officers.tsv
sed -i 's/^Create.With.Care/62/i' organization-officers.tsv
sed -i 's/^Crew.Rowing/63/i' organization-officers.tsv
sed -i 's/^Cru/64/i' organization-officers.tsv
sed -i 's/^CWIT.Student.Council/65/i' organization-officers.tsv
sed -i 's/^Cyber.Defense.Team/66/i' organization-officers.tsv
sed -i 's/^Cycling.Club/67/i' organization-officers.tsv
sed -i 's/^Dagorhir/68/i' organization-officers.tsv
sed -i 's/^Debate.Club/69/i' organization-officers.tsv
sed -i 's/^Delta.Phi.Epsilon/70/i' organization-officers.tsv
sed -i 's/^Delta.Sigma.Theta.Sorority..Inc/71/i' organization-officers.tsv
sed -i 's/^Destination.H.O.M.E...Helping.Others.More.Everyday./72/i' organization-officers.tsv
sed -i 's/^Disciples.on.Campus/73/i' organization-officers.tsv
sed -i 's/^Dog.Collar.Comedy.Troupe/74/i' organization-officers.tsv
sed -i 's/^Economics.Council/75/i' organization-officers.tsv
sed -i 's/^Education.Council.of.Majors/76/i' organization-officers.tsv
sed -i 's/^Engineers.Without.Borders/77/i' organization-officers.tsv
sed -i 's/^Environmental.Task.Force/78/i' organization-officers.tsv
sed -i 's/^Equestrian.Club/79/i' organization-officers.tsv
sed -i 's/^Ethics.Bowl.Team/80/i' organization-officers.tsv
sed -i 's/^Ethiopian.Eritrean.Student.Association/81/i' organization-officers.tsv
sed -i 's/^Fencing.Club/82/i' organization-officers.tsv
sed -i 's/^Filipino.American.Student.Association/83/i' organization-officers.tsv
sed -i 's/^Filmmakers.Anonymous/84/i' organization-officers.tsv
sed -i 's/^Food.Recovery.Network/85/i' organization-officers.tsv
sed -i 's/^French.Club/86/i' organization-officers.tsv
sed -i 's/^Game.Developer..8217.s.Club/87/i' organization-officers.tsv
sed -i 's/^Garden..The/88/i' organization-officers.tsv
sed -i 's/^Geography.and.Environmental.Systems.Council.of.Majors/89/i' organization-officers.tsv
sed -i 's/^Girl.Up/90/i' organization-officers.tsv
sed -i 's/^Global.Brigades/91/i' organization-officers.tsv
sed -i 's/^GlobeMed/92/i' organization-officers.tsv
sed -i 's/^Golden.Key.International.Honour.Society/93/i' organization-officers.tsv
sed -i 's/^Gospel.Choir/94/i' organization-officers.tsv
sed -i 's/^Habitat.for.Humanity/95/i' organization-officers.tsv
sed -i 's/^HackUMBC/96/i' organization-officers.tsv
sed -i 's/^Health.Administration..amp..Policy.C.O.M./97/i' organization-officers.tsv
sed -i 's/^Hellenic.Student.Association/98/i' organization-officers.tsv
sed -i 's/^Hillel.Student.Organization/99/i' organization-officers.tsv
sed -i 's/^Hindu.Students.Council/100/i' organization-officers.tsv
sed -i 's/^Hispanic.Latino.Student.Union/101/i' organization-officers.tsv
sed -i 's/^History.Student.Council/102/i' organization-officers.tsv
sed -i 's/^Honors.College.Council/103/i' organization-officers.tsv
sed -i 's/^Humans.vs..Zombies.Club..UMBC/104/i' organization-officers.tsv
sed -i 's/^Humble.Rumble..The/105/i' organization-officers.tsv
sed -i 's/^Ice.Hockey.Club/106/i' organization-officers.tsv
sed -i 's/^Information.Systems.Council.of.Majors/107/i' organization-officers.tsv
sed -i 's/^Information.Systems.Security.Association/108/i' organization-officers.tsv
sed -i 's/^Institute.of.Electrical.and.Electronics.Engineers/109/i' organization-officers.tsv
sed -i 's/^Interfraternity.Council/110/i' organization-officers.tsv
sed -i 's/^Intervarsity.Christian.Fellowship/111/i' organization-officers.tsv
sed -i 's/^Investing.and.Trading.Club/112/i' organization-officers.tsv
sed -i 's/^Ishara..The.Indian.Classical.Dance.Team/113/i' organization-officers.tsv
sed -i 's/^Japanese.Student.Association/114/i' organization-officers.tsv
sed -i 's/^Jujitsu.Club/115/i' organization-officers.tsv
sed -i 's/^Korean.Bible.Study/116/i' organization-officers.tsv
sed -i 's/^Korean.Dance.Club/117/i' organization-officers.tsv
sed -i 's/^Korean.Student.Association/118/i' organization-officers.tsv
sed -i 's/^Lacrosse..Men..8217.s./119/i' organization-officers.tsv
sed -i 's/^Lacrosse..Women..8217.s./120/i' organization-officers.tsv
sed -i 's/^Lambda.Chi.Alpha.Fraternity/121/i' organization-officers.tsv
sed -i 's/^Lambda.Theta.Alpha.Latin.Sorority..Inc/122/i' organization-officers.tsv
sed -i 's/^Latin.Dance.Club/123/i' organization-officers.tsv
sed -i 's/^League.of.Legends.Club/124/i' organization-officers.tsv
sed -i 's/^Lemon.Aide.for.the.Children/125/i' organization-officers.tsv
sed -i 's/^Lending.a.Helping.Paw/126/i' organization-officers.tsv
sed -i 's/^LGBTQStudent.Union/127/i' organization-officers.tsv
sed -i 's/^Linguistics.Club/128/i' organization-officers.tsv
sed -i 's/^Linux.User..8217.s.Group/129/i' organization-officers.tsv
sed -i 's/^Living.Water.Christian.Fellowship/130/i' organization-officers.tsv
sed -i 's/^Lutheran.and.Episcopal.Campus.Ministry/131/i' organization-officers.tsv
sed -i 's/^Major.Definition/132/i' organization-officers.tsv
sed -i 's/^Mama..8217.s.Boys/133/i' organization-officers.tsv
sed -i 's/^Management.of.Aging.Services.Council.of.Majors/134/i' organization-officers.tsv
sed -i 's/^Media.and.Communication.Studies.Council.of.Majors/135/i' organization-officers.tsv
sed -i 's/^Meditation.at.UMBC/136/i' organization-officers.tsv
sed -i 's/^MEDLIFE/137/i' organization-officers.tsv
sed -i 's/^Minority.Association.of.Pre.Medical.Students..MAPS./138/i' organization-officers.tsv
sed -i 's/^Mock.Trial.Team/139/i' organization-officers.tsv
sed -i 's/^Model.African.Union/140/i' organization-officers.tsv
sed -i 's/^Model.United.Nations/141/i' organization-officers.tsv
sed -i 's/^Moot.Court.Club/142/i' organization-officers.tsv
sed -i 's/^Multicultural.Greek.Council/143/i' organization-officers.tsv
sed -i 's/^Musical.Theatre.Club/144/i' organization-officers.tsv
sed -i 's/^Muslim.Student.Association/145/i' organization-officers.tsv
sed -i 's/^National.Alliance.on.Mental.Illness/146/i' organization-officers.tsv
sed -i 's/^National.Pan.Hellenic.Council/147/i' organization-officers.tsv
sed -i 's/^National.Society.of.Black.Engineers/148/i' organization-officers.tsv
sed -i 's/^National.Society.of.Collegiate.Scholars/149/i' organization-officers.tsv
sed -i 's/^Nepali.Student.Association/150/i' organization-officers.tsv
sed -i 's/^Network.of.Entrepreneurs/151/i' organization-officers.tsv
sed -i 's/^Orthodox.Christian.Fellowship/152/i' organization-officers.tsv
sed -i 's/^Outdoor.Recreation.Club/153/i' organization-officers.tsv
sed -i 's/^Pagan.Student.Union/154/i' organization-officers.tsv
sed -i 's/^Pakistani.Student.Association..PakSA./155/i' organization-officers.tsv
sed -i 's/^Pandemic.Steel.Drum.Band/156/i' organization-officers.tsv
sed -i 's/^Panhellenic.Association/157/i' organization-officers.tsv
sed -i 's/^Parents.Club/158/i' organization-officers.tsv
sed -i 's/^Persian.Student.Association/159/i' organization-officers.tsv
sed -i 's/^Phi.Alpha.National.Social.Work.Honor.Society/160/i' organization-officers.tsv
sed -i 's/^Phi.Beta.Sigma.Fraternity..Inc./161/i' organization-officers.tsv
sed -i 's/^Phi.Delta.Epsilon.International.Medical.Fraternity/162/i' organization-officers.tsv
sed -i 's/^Phi.Kappa.Sigma/163/i' organization-officers.tsv
sed -i 's/^Phi.Mu.Fraternity.for.Women/164/i' organization-officers.tsv
sed -i 's/^Phi.Sigma.Sigma/165/i' organization-officers.tsv
sed -i 's/^Philosophers.Anonymous/166/i' organization-officers.tsv
sed -i 's/^Photography.Club/167/i' organization-officers.tsv
sed -i 's/^Physical..Health..Lifestyle..Excellence...PHLEx./168/i' organization-officers.tsv
sed -i 's/^Pi.Kappa.Phi/169/i' organization-officers.tsv
sed -i 's/^Political.Science.Council.of.Majors/170/i' organization-officers.tsv
sed -i 's/^Pre.Dental.Society/171/i' organization-officers.tsv
sed -i 's/^Pre.Law.Society/172/i' organization-officers.tsv
sed -i 's/^Pre.Medical.Society/173/i' organization-officers.tsv
sed -i 's/^Pre.Nursing.Society/174/i' organization-officers.tsv
sed -i 's/^Pre.Optometry.Society/175/i' organization-officers.tsv
sed -i 's/^Pre.Osteopathic.Medicine.Society/176/i' organization-officers.tsv
sed -i 's/^Pre.Pharmacy.Society/177/i' organization-officers.tsv
sed -i 's/^Pre.Physical.Therapy.Society/178/i' organization-officers.tsv
sed -i 's/^Pre.Physician.Assistant.Society/179/i' organization-officers.tsv
sed -i 's/^Pre.Veterinary.Society/180/i' organization-officers.tsv
sed -i 's/^Progressives/181/i' organization-officers.tsv
sed -i 's/^Psi.Chi.Honor.Society..Psychology./182/i' organization-officers.tsv
sed -i 's/^Reach.Initiative..The/183/i' organization-officers.tsv
sed -i 's/^Resident.Student.Association/184/i' organization-officers.tsv
sed -i 's/^Retriever.Bhangra/185/i' organization-officers.tsv
sed -i 's/^Retriever.Design.Club/186/i' organization-officers.tsv
sed -i 's/^Retriever.Robotics/187/i' organization-officers.tsv
sed -i 's/^Retriever.Weekly/188/i' organization-officers.tsv
sed -i 's/^Rifle.and.Pistol.Club..Firearm.Safety.and.Education./189/i' organization-officers.tsv
sed -i 's/^Rock.Climbing.Club..UMBC/190/i' organization-officers.tsv
sed -i 's/^Rockets.and.More/191/i' organization-officers.tsv
sed -i 's/^Rotaract.Club/192/i' organization-officers.tsv
sed -i 's/^Rugby.Club..Men..8217.s./193/i' organization-officers.tsv
sed -i 's/^Rugby.Club..Women..8217.s./194/i' organization-officers.tsv
sed -i 's/^Running.Club/195/i' organization-officers.tsv
sed -i 's/^Russian.Club/196/i' organization-officers.tsv
sed -i 's/^SAE.Snowmobile.Club/197/i' organization-officers.tsv
sed -i 's/^S.T.A.R..Program..The/198/i' organization-officers.tsv
sed -i 's/^Sailing.Club..amp..Team/199/i' organization-officers.tsv
sed -i 's/^Salvation.and.Praise/200/i' organization-officers.tsv
sed -i 's/^Scuba.Diving.Club/201/i' organization-officers.tsv
sed -i 's/^Sigma.Alpha.Lambda/202/i' organization-officers.tsv
sed -i 's/^Sign.of.Life/203/i' organization-officers.tsv
sed -i 's/^Sikh.Student.Association/204/i' organization-officers.tsv
sed -i 's/^Soccer..Men..8217.s./205/i' organization-officers.tsv
sed -i 's/^Soccer..Women..8217.s./206/i' organization-officers.tsv
sed -i 's/^Social.Work.Student.Association/207/i' organization-officers.tsv
sed -i 's/^Society.for.Advancement.of.Chicanos.Hispanics.and.Native.Americans.in.Science.at.UMBC/208/i' organization-officers.tsv
sed -i 's/^Society.of.Asian.Scientists.and.Engineers..SASE./209/i' organization-officers.tsv
sed -i 's/^Society.of.Automotive.Engineers/210/i' organization-officers.tsv
sed -i 's/^Society.of.Hispanic.Professional.Engineers/211/i' organization-officers.tsv
sed -i 's/^Society.of.Physics.Students..SPS./212/i' organization-officers.tsv
sed -i 's/^Society.of.Women.Engineers/213/i' organization-officers.tsv
sed -i 's/^South.Asian.Students.Association/214/i' organization-officers.tsv
sed -i 's/^Spanish.Conversation.Club/215/i' organization-officers.tsv
sed -i 's/^Splash..UMBC/216/i' organization-officers.tsv
sed -i 's/^Sri.Lankan.Student.Association..SLSA./217/i' organization-officers.tsv
sed -i 's/^Stilettos..The/218/i' organization-officers.tsv
sed -i 's/^Student.Actuarial.Society/219/i' organization-officers.tsv
sed -i 's/^Student.Alumni.Association/220/i' organization-officers.tsv
sed -i 's/^Student.Climate.Change.Coalition/221/i' organization-officers.tsv
sed -i 's/^Student.Events.Board/222/i' organization-officers.tsv
sed -i 's/^Student.Government.Association/223/i' organization-officers.tsv
sed -i 's/^Student.Athlete.Advisory.Committee/224/i' organization-officers.tsv
sed -i 's/^Students.for.Environmental.Awareness/225/i' organization-officers.tsv
sed -i 's/^Students.for.Life/226/i' organization-officers.tsv
sed -i 's/^Students.Helping.Honduras/227/i' organization-officers.tsv
sed -i 's/^Super.Smash.Bros..Club/228/i' organization-officers.tsv
sed -i 's/^Taal.Capella/229/i' organization-officers.tsv
sed -i 's/^Table.Tennis.Club/230/i' organization-officers.tsv
sed -i 's/^Tae.Kwon.Do.Club/231/i' organization-officers.tsv
sed -i 's/^Tau.Beta.Pi..Engineering./232/i' organization-officers.tsv
sed -i 's/^Tau.Kappa.Epsilon/233/i' organization-officers.tsv
sed -i 's/^Tau.Sigma.National.Honor.Society/234/i' organization-officers.tsv
sed -i 's/^Tennis.Club/235/i' organization-officers.tsv
sed -i 's/^Theatre.Council.of.Majors/236/i' organization-officers.tsv
sed -i 's/^Triangle.Fraternity/237/i' organization-officers.tsv
sed -i 's/^Ultimate.Frisbee..Women..8217.s./238/i' organization-officers.tsv
sed -i 's/^Ultimate.Frisbee.Team/239/i' organization-officers.tsv
sed -i 's/^UMBC.Gaming/240/i' organization-officers.tsv
sed -i 's/^UMBC.Raascals/241/i' organization-officers.tsv
sed -i 's/^UMBeatsClub/242/i' organization-officers.tsv
sed -i 's/^UNICEF.Club/243/i' organization-officers.tsv
sed -i 's/^United.Christian.Council/244/i' organization-officers.tsv
sed -i 's/^United.States.Institute.of.Theatre.Technology.Student.Chapter/245/i' organization-officers.tsv
sed -i 's/^Viet.Nam.Medical.Assistance.Program..VNMAP./246/i' organization-officers.tsv
sed -i 's/^Vietnamese.Student.Association/247/i' organization-officers.tsv
sed -i 's/^VITA.Tax.Preparation/248/i' organization-officers.tsv
sed -i 's/^Volleyball..Men..8217.s./249/i' organization-officers.tsv
sed -i 's/^Volleyball..Women..8217.s./250/i' organization-officers.tsv
sed -i 's/^WMBC/251/i' organization-officers.tsv
sed -i 's/^Women.Involved.in.Learning.and.Leadership..WILL./252/i' organization-officers.tsv
sed -i 's/^Wrestling.Team/253/i' organization-officers.tsv
sed -i 's/^Wushu.Tai.Chi.Club/254/i' organization-officers.tsv
sed -i 's/^Zeta.Sigma.Chi.Multicultural.Sorority..Inc/255/i' organization-officers.tsv
sed -i 's/^Alpha.Omega.Campus.Ministry/256/i' organization-officers.tsv
sed -i 's/^American.Mock.World.Health.Organization/257/i' organization-officers.tsv
sed -i 's/^Book.Club/258/i' organization-officers.tsv
sed -i 's/^Chinese.Bible.Study.Fellowship/259/i' organization-officers.tsv
sed -i 's/^Cooking.Club/260/i' organization-officers.tsv
sed -i 's/^Dance.Council.of.Majors/261/i' organization-officers.tsv
sed -i 's/^Foundation.for.International.Medical.Relief.of.Children/262/i' organization-officers.tsv
sed -i 's/^Gearheads/263/i' organization-officers.tsv
sed -i 's/^Jewish.Learning.Connection/264/i' organization-officers.tsv
sed -i 's/^LGBTQ.Student.Union/265/i' organization-officers.tsv
sed -i 's/^Overwatch.Club/266/i' organization-officers.tsv
sed -i 's/^Paintball.Club/267/i' organization-officers.tsv
sed -i 's/^Pakistani.Student.Association..PaskSA./268/i' organization-officers.tsv
sed -i 's/^Retrievers.Battalion/269/i' organization-officers.tsv
sed -i 's/^Retriever.Poets/270/i' organization-officers.tsv
sed -i 's/^Saudi.Student.Association/271/i' organization-officers.tsv
sed -i 's/^Society.of.Asian.Scientists.and.Engineers/272/i' organization-officers.tsv
sed -i 's/^SolarRetrievers/273/i' organization-officers.tsv
sed -i 's/^Students.for.Christ.Campus.Ministry/274/i' organization-officers.tsv
sed -i 's/^The.American.Institute.of.Aeronautics.and.Astronautics..AIAA./275/i' organization-officers.tsv
sed -i 's/^The.Charm.City.Connection/276/i' organization-officers.tsv
sed -i 's/^The.Garden/277/i' organization-officers.tsv
sed -i 's/^The.Humble.Rumble/278/i' organization-officers.tsv
sed -i 's/^The.Reach.Initiative/279/i' organization-officers.tsv
sed -i 's/^The.S.T.A.R..Program/280/i' organization-officers.tsv
sed -i 's/^We.Believe.You/281/i' organization-officers.tsv
sed -i 's/^Young.Life/282/i' organization-officers.tsv
